name: 'publish package to npm'

# Deploys next patch version from the HEAD of the main branch.
# Manually update package.json for major/minor version changes when required.

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org

      - name: install packages
        run: npm install

      - name: build
        run: npm run build

      - name: set git user
        uses: git-actions/set-user@v1

      - name: Update patch version
        run: npm version patch -m "Deploy version %s to npm"

      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMAUTHTOKEN}}

      - name: push version update
        run: git push
